mode = "dark"

accent = "#a4735b"
selection = "#302e29"
muted = "#605d57"

background = "#090704"
dark_background = "#070503"
darker_background = "#050402"
lighter_background = "#22201d"

foreground = "#DCB39B"
dark_foreground = "#a58674"
light_foreground = "#e1beaa"
bright_foreground = "#e5c6b4"

red = "#b28e6b"
yellow = "#ffeba9"
orange = "#be9f81"
green = "#dcbf87"
cyan = "#f2d98b"
blue = "#a4735b"
magenta = "#d79e76"
brown = "#725f4d"

bright_red = "#cea275"
bright_yellow = "#ffe996"
bright_green = "#fad48a"
bright_cyan = "#ffef8d"
bright_blue = "#c28567"
bright_magenta = "#f8b07c"
