# Background and foreground colors
background = #090704
foreground = #DCB39B

# Standard colors
palette = 0=#090704
palette = 1=#b28e6b
palette = 2=#dcbf87
palette = 3=#ffeba9
palette = 4=#a4735b
palette = 5=#d79e76
palette = 6=#f2d98b
palette = 7=#DCB39B

# Bright colors
palette = 8=#605d57
palette = 9=#cea275
palette = 10=#fad48a
palette = 11=#ffe996
palette = 12=#c28567
palette = 13=#f8b07c
palette = 14=#ffef8d
palette = 15=#fcf4ea
