$color = rgba(9, 7, 4, 1)
$inner_color = rgba(9, 7, 4, 0.66)
$outer_color = rgba(215, 158, 118, 1)
$font_color = rgba(220, 179, 155, 1)
$placeholder_color = rgba(220, 179, 155, 0.7)
$check_color = rgba(242, 217, 139, 1)
