background            #090704
foreground            #DCB39B

# black
color0  #090704
color8  #605d57

# red
color1  #b28e6b
color9  #cea275

# green
color2  #dcbf87
color10 #fad48a

# yellow
color3  #ffeba9
color11 #ffe996

# blue
color4  #a4735b
color12 #c28567

# magenta
color5  #d79e76
color13 #f8b07c

#cyan
color6  #f2d98b
color14 #ffef8d

#white
color7  #DCB39B
color15 #fcf4ea


